Coat
====
Marco Herrn <marco@mherrn.de>
2020-12-12
:compat-mode!:
:toc:
:homepage: https://github.com/poiu-de/coat
:download-page: https://github.com/poiu-de/coat/releases
:javadoc-url: https://javadoc.io/doc/de.poiu.coat/coat/
:license-link: https://github.com/poiu-de/coat/blob/master/LICENSE.txt
:user_guide: https://poiu-de.github.io/coat/docs/user_guide/
:log4j2-jul-bridge: https://logging.apache.org/log4j/2.x/log4j-jul/index.html
:slf4j-jul-bridge: https://www.slf4j.org/legacy.html#jul-to-slf4j
:source-highlighter: prettify
:coat-version: 0.0.4

[.float-group]
--
image:coat-icon.svg[Coat,role="right", width="75"]
Coat - Config of Annotated Types

Easy and typesafe config objects.
--


What is Coat
------------

Coat is an annotation processor to generate classes for reading
configuration values into typesafe objects.

Short Usage
-----------

1. Define an interface representing your config object.
+
[source,java]
----
import de.poiu.coat.annotation.Coat;

@Coat.Config
public interface MyConfig {
  public String appName();

  public int listenPort();

  public Optional<String> description();
}
----

2. Let the Coat annotation processor create the concrete implementation.
3. Use the generated class.
+
[source,java]
----
final MyConfig config= new ImmutableMyConfig(new File("/path/to/config.properties"));

try {
  config.validate();
} catch (final ConfigValidationException ex) {
  System.err.println("Error in config file:\n" + ex.getValidationResult().toString());
  System.exit(1);
}

final String appName= config.appName();
final int listenPort= config.listenPort();
config.description().ifPresent(
  …
);
----


Prerequisites
-------------

Coat has no runtime dependencies on other libraries.

The annotation processor has some dependencies on other libraries (which is
why it is recommended to use maven as it resolves those dependencies
automatically), but non of them are needed at runtime.

// FIXME: Should we change this requirement?
Coat can be used with Java 11 or higher.


Installation
------------

To use Coat in a maven based project use the following maven coordinates:

[source,xml,subs="verbatim,attributes"]
----
    <!-- Contains the annotation processor. Not needed at runtime. -->
    <dependency>
      <groupId>de.poiu.coat</groupId>
      <artifactId>coat-processor</artifactId>
      <version>{coat-version}</version>
      <scope>provided</scope>
    </dependency>

    <!-- Contains the converters and base classes. Needed at runtime. -->
    <dependency>
      <groupId>de.poiu.coat</groupId>
      <artifactId>coat-runtime</artifactId>
      <version>{coat-version}</version>
    </dependency>
----

Otherwise download the jar-file of Coat from the {download-page}[Download
page] and put it into the classpath of your application.


Usage
-----

For a more thorough description of the possibilities of Coat read the
{user_guide}[User Guide].


Logging
-------

There are a few cases this library issues some logging statements (actually
only when reading from a `java.util.Properties` object that contains
non-String entries, which should never be the case anyway).

Coat uses the `java.lang.System.Logger` for that purpose, which is
available since Java 9.

The System.Logger is supported in log4j2 since version 2.13.2. To use it
include the `log4j-jpl` jar.

The System.Logger is https://jira.qos.ch/browse/SLF4J-442[not yet
supported] in slf4j/logback. For writing an adapter the
https://github.com/qos-ch/slf4j/pull/232[PR of Nicolai Parlog] can be
used as reference. Also a (rudimentary) example of writing such an adapter
is described on
https://www.logicbig.com/tutorials/core-java-tutorial/java-9-changes/platform-logging.html[LogicBig].

If no adapter is found at runtime the System.Logger defaults to using
java.util.logging.

// There are no known bugs at the moment
//Known Bugs and Deficiencies
//---------------------------



License
-------

Coat is licensed under the terms of the link:{license-link}[Apache license 2.0].
